name: Build Swift SDK

on:
  push:
    branches: [main, develop]
    paths:
      - 'graphiti-swift/**'
      - '.github/workflows/swift-build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'graphiti-swift/**'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        working-directory: ./graphiti-swift
        run: swift build -c release

      - name: Run tests
        working-directory: ./graphiti-swift
        run: swift test

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:6.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        working-directory: ./graphiti-swift
        run: swift build -c release

      - name: Run tests
        working-directory: ./graphiti-swift
        run: swift test
